done
mate-academy/react_goods-selector pull request #101
Opened 2020-11-06 13:02 UTC by AntonChetverykMA

2020-11-06 20:02 UTC, vpolets requested changes
чекаю рішення з робочим ctrl, ти це можеш зробити.

2020-11-06 20:02 UTC, vpolets commented on src/App.js
> +              }}
зроби це стилями і навішай клас

2020-11-06 20:02 UTC, vpolets commented on src/App.js
> +              <li className={selected === item ? 'selected' : ''}>{item}</li>
```suggestion
              <li className={selected === item && 'selected'}>{item}</li>
```

2020-11-08 12:20 UTC, AntonChetverykMA commented on src/App.js
> +              }}
пофиксил

2020-11-08 12:20 UTC, AntonChetverykMA commented on src/App.js
> +              <li className={selected === item ? 'selected' : ''}>{item}</li>
Так как ты написал, не получается сделать, оно пишет что в className нельзя передать boolean(slected === item)

2020-11-08 12:23 UTC, AntonChetverykMA commented
> чекаю рішення з робочим ctrl, ти це можеш зробити.

на счет этого не понял, там в advanced , сделать кнопки add remove, и возможность добавлять в список, это я сделал

2020-11-09 11:02 UTC, vpolets commented on src/App.js
> +              <li className={selected === item ? 'selected' : ''}>{item}</li>
тоді рекомендую користуватися бібліотукою classnames
https://www.npmjs.com/package/classnames

2020-11-09 11:04 UTC, vpolets approved these changes
не бачу посилання на gh-pages, додавай його в наступні  PR
на рахунок ctrl, Міша зменшив умову, не побачив це)

2023-02-14 16:16 UTC, closed without merging