done
mate-academy/react_goods-selector pull request #1046
Opened 2022-10-27 10:44 UTC by p-omogit-e

[DEMO LINK](https://p-omogit-e.github.io/react_goods-selector/)

2022-10-27 17:36 UTC, AlisaVlasova requested changes

2022-10-27 17:36 UTC, AlisaVlasova commented on src/App.tsx
> +          {selectedGood === ''
```suggestion
          {!selectedGood
```

2022-10-27 17:36 UTC, AlisaVlasova commented on src/App.tsx
> +                        }}
```suggestion
                        onClick={() => {
                          this.saveHandler('');
                        }}
```

2022-11-03 08:53 UTC, tetiana-ivanchenko requested changes

2022-11-03 08:53 UTC, tetiana-ivanchenko commented on src/App.tsx
> +                        }}
please, fix all coments, before re-requesting review

2022-11-03 19:01 UTC, AlisaVlasova requested changes

2022-11-03 19:01 UTC, AlisaVlasova commented on src/App.tsx
> +              <h1 className="title is-flex is-align-items-center">
```suggestion
        <h1 className="title">
          {!selectedGood
            ? 'No goods selected'
            : (
```
не став `h1` всередину іншого `h1`, класи `is-flex is-align-items-center` можна виставити по умові `selectedGood`

2022-11-18 19:01 UTC, AlisaVlasova approved these changes

2025-12-17 21:29 UTC, closed without merging