Develop
mate-academy/react_goods-selector pull request #1080
Opened 2022-11-21 17:29 UTC by andriy-shymkiv

[DEMO LINK](https://andriy-shymkiv.github.io/react_goods-selector/)

2022-11-22 11:55 UTC, Artem66 requested changes

2022-11-22 11:55 UTC, Artem66 commented on src/App.tsx
> +              onClick={() => {
you can create method and reuse it on remove button
 checklist#2 Create separate methods instead of creating inline

2022-11-22 11:55 UTC, Artem66 commented on src/App.tsx
> +                          this.setState({ selectedGood: good });
checklist#2 Create separate methods instead of creating inline

2022-11-22 11:55 UTC, Artem66 commented on src/App.tsx
> +                          this.setState({ selectedGood: '' });
checklist#2 Create separate methods instead of creating inline

2022-11-22 13:48 UTC, Artem66 approved these changes

2022-11-23 08:28 UTC, denys-danyliuk approved these changes

2022-11-23 08:28 UTC, denys-danyliuk commented on src/App.tsx
> +  chooseSelectedGood = (good: string) => {
```suggestion
  selectGood = (good: string) => {
```

2022-11-23 08:28 UTC, denys-danyliuk commented on src/App.tsx
> +                  { 'has-background-success-light': good === selectedGood },
```suggestion
                  { 
                    'has-background-success-light': good === selectedGood 
                  },
```

2022-11-23 08:28 UTC, denys-danyliuk commented on src/App.tsx
> +                <td data-cy="GoodTitle" className="is-vcentered">{good}</td>
```suggestion
                <td data-cy="GoodTitle" className="is-vcentered">
                  {good}
                </td>
```

2024-03-27 08:41 UTC, closed without merging