develop
mate-academy/react_goods-selector pull request #116
Opened 2021-01-18 10:15 UTC by Layrovell

[DEMO LINK](https://Layrovell>.github.io/react_goods-selector/)

2021-01-18 20:26 UTC, Serhii-Alieksieievych approved these changes
не впевнений що так має бути, але в вимогах це прямо не забороняється, тому апруваю)
https://prnt.sc/x5kdpd

2021-01-19 07:42 UTC, varseniuk requested changes
Serhii is right. You should add only one instance of any good at a time. Fix it. Everything else is ok

2021-01-19 09:27 UTC, varseniuk requested changes
Still can add multiple items

2021-01-19 09:27 UTC, varseniuk commented on src/components/Selector/Selector.jsx
> +  };
Your function still adds multiple same items to the list. You can prevent this by adding check here like
`if(!this.state.selectedGoods.includes(item)) {...}`

2021-01-19 15:25 UTC, varseniuk approved these changes
👍

2023-04-05 21:31 UTC, closed without merging