Add React Goods selector
mate-academy/react_goods-selector pull request #1190
Opened 2023-01-03 13:50 UTC by Ruslan-Pashkov

[DEMO LINK](https://ruslan-pashkov.github.io/react_goods-selector/)

2023-01-08 19:30 UTC, Anastasia4sik requested changes
Fix a few things

2023-01-08 19:30 UTC, Anastasia4sik commented on src/App.tsx
> +                        onClick={() => this.selectItem(good)}
Checklist p.3

2023-01-08 19:30 UTC, Anastasia4sik commented on src/App.tsx
> +                  onClick={() => this.setState({ selectedGood: '' })}
Checklist p.3

2023-01-10 09:36 UTC, Ihor-Karpyn requested changes
Almost done

2023-01-10 09:36 UTC, Ihor-Karpyn commented on src/App.tsx
> +    const condition = item === this.state.selectedGood;
Let's think more about variable name

2023-01-10 09:36 UTC, Ihor-Karpyn commented on src/App.tsx
> +    const valueToSet = condition ? '' : item;
I hope this variable redundant
```suggestion
```

2023-01-10 09:36 UTC, Ihor-Karpyn commented on src/App.tsx
> +                {/* eslint-disable-next-line jsx-a11y/control-has-associated-label */}
Let's add a label, the linter doesn't exist to disable it

2023-01-10 09:36 UTC, Ihor-Karpyn commented on src/App.tsx
> +              goods.map(good => {
```suggestion
            {goods.map(good => {
```

2023-01-11 16:27 UTC, Ihor-Karpyn approved these changes

2023-02-20 15:03 UTC, closed without merging