solution
mate-academy/react_goods-selector pull request #1246
Opened 2023-01-25 15:07 UTC by igor-kashchenko

[DEMO LINK](https://igor-kashchenko.github.io/react_goods-selector/)

2023-01-27 11:10 UTC, OlhaYevstifieieva approved these changes
Nice job)

2023-01-30 07:23 UTC, Anna-Tkachenko requested changes

2023-01-30 07:23 UTC, Anna-Tkachenko commented on src/App.tsx
> +              {selectedGood}
you can also write it in 1 row instead of 3
```suggestion
              {`${selectedGood} is selected`}
```

2023-01-30 07:23 UTC, Anna-Tkachenko commented on src/App.tsx
> +              {/* eslint-disable-next-line jsx-a11y/control-has-associated-label */}
will be better to find solution instead of disabling linter

2023-01-30 07:23 UTC, Anna-Tkachenko commented on src/App.tsx
> +          : (<h1 className="title">No goods selected</h1>)}
```suggestion
          : (
            <h1 className="title">No goods selected</h1>
          )}
```

2023-01-30 07:23 UTC, Anna-Tkachenko commented on src/App.tsx
> +                className={classNames('',
empty string as class name is redundant here

2023-01-30 07:23 UTC, Anna-Tkachenko commented on src/App.tsx
> +                  { 'has-background-success-light': good === selectedGood })}
you check is current good selected several times
let's create separate function or boolean variable that will store or calculate it one time, and will use it where you need it

2023-01-30 14:35 UTC, Anna-Tkachenko approved these changes
⭐️

2024-11-08 14:13 UTC, closed without merging