develop
mate-academy/react_goods-selector pull request #13
Opened 2020-09-02 16:35 UTC by krajnova

[DEMO LINK](https://krajnova.github.io/react_goods-selector/)

2020-09-02 16:48 UTC, nanccyy approved these changes
Good!

2020-09-03 11:44 UTC, vsm2k17 requested changes

2020-09-03 11:44 UTC, vsm2k17 commented on src/App.js
> +    const selected = document.querySelector('.selected');
в реакті нам не потрібен querySelector ми можем визначати класи динамічно перед тим як відрендерити, єдине що потрібно це передати в state значення яке буде показувати вибраний елемент і при рендері перевіряти чи він збігається з тим який ми рендерим , якщо так то додаєм клас якщо ні то не додаєм

2020-09-03 11:44 UTC, vsm2k17 commented on src/App.js
> +    this.setState({ selectedGood: 'no item selected' });
цього рядка повинно бути достатньо решта зайве

2020-09-03 11:44 UTC, vsm2k17 commented on src/App.js
> +    this.setState({ selectedGood: element.textContent });
та сама ситуація це єдиний рядок який тобі потрібен в цій ф-її

2020-09-03 11:44 UTC, vsm2k17 commented on src/App.js
> +            {this.state.selectedGood}
деструктуруй SelectedGood щоб не писати кожен раз this.state

2020-09-03 11:44 UTC, vsm2k17 commented on src/App.js
> +                className="good"
тут додавати клас при умові що item.good ===selectedGood

2020-09-03 16:22 UTC, vsm2k17 approved these changes

2025-01-27 11:16 UTC, closed without merging