Solution
mate-academy/react_goods-selector pull request #1350
Opened 2023-03-08 16:45 UTC by stanislavcodes

[DEMO LINK](https://stanislavcodes.github.io/react_goods-selector/)

2023-03-09 10:32 UTC, lilia-obushenko approved these changes
GJ!

2023-03-13 15:12 UTC, illiarerun requested changes

2023-03-13 15:12 UTC, illiarerun commented on src/App.tsx
> +                  'has-background-success-light': selectedGood === good,
you repeat this check 2 times, create a variable

2023-03-13 15:12 UTC, illiarerun commented on src/App.tsx
> +                      onClick={() => this.handleClearGood()}
[checklist](https://github.com/mate-academy/react_goods-selector/blob/master/checklist.md) 3rd item

2023-03-14 12:28 UTC, illiarerun approved these changes

2026-07-06 09:21 UTC, closed without merging