solution
mate-academy/react_goods-selector pull request #1398
Opened 2023-03-20 12:03 UTC by Nordexz

[DEMO LINK](https://nordexz.github.io/react_goods-selector/)

2023-03-21 17:18 UTC, sergii-nosachenko requested changes

2023-03-21 17:18 UTC, sergii-nosachenko commented on src/App.tsx
> +  state = {
Make it Readonly

2023-03-21 17:18 UTC, sergii-nosachenko commented on src/App.tsx
> +  setGood = (product: string) => {
Use `change` instead. Prefix `set` is used for state hooks.

2023-03-21 17:18 UTC, sergii-nosachenko commented on src/App.tsx
> +          selectedGood
```suggestion
        {selectedGood
```

2023-03-21 17:18 UTC, sergii-nosachenko commented on src/App.tsx
> +                {/* eslint-disable-next-line jsx-a11y/control-has-associated-label */}
Don't disable linter, use `aria-label` instead

2023-03-21 17:18 UTC, sergii-nosachenko commented on src/App.tsx
> +                      !isSelected
```suggestion
                    {!isSelected
```

2023-03-27 12:03 UTC, illiarerun approved these changes

2025-09-29 20:19 UTC, closed without merging