add task solution
mate-academy/react_goods-selector pull request #1564
Opened 2023-05-30 19:10 UTC by NickMitchell61

[DEMO LINK](https://NickMitchell61.github.io/react_goods-selector/)

2023-06-02 08:27 UTC, dinaminahi requested changes
Good job! 👍 
Let's just fix few things to improve readability

2023-06-02 08:27 UTC, dinaminahi commented on src/App.tsx
> +                }}
Let's create a separate function to clear the good and to set selectedGood

2023-06-02 08:27 UTC, dinaminahi commented on src/App.tsx
> +                    )}
```suggestion
                  {selectedGood === item
                    ? (
                      <button
                        data-cy="RemoveButton"
                        type="button"
                        className="button is-info"
                        onClick={() => {
                          this.setState({ selectedGood: '' });
                        }}
                      >
                        -
                      </button>
                    ) : (
                       <button
                        data-cy="AddButton"
                        type="button"
                        className="button"
                        onClick={() => {
                          this.setState({ selectedGood: item });
                        }}
                      >
                        +
                      </button>
                    )}
```

2023-06-05 09:28 UTC, silchyn approved these changes

2023-06-05 09:28 UTC, silchyn commented on src/App.tsx
> +        {!selectedGood
it's better for understanding to have this condition positive instead of negative (`selectedGood` instead of `!selectedGood`)

2023-07-05 08:01 UTC, closed without merging