solution
mate-academy/react_goods-selector pull request #16
Opened 2020-09-03 06:32 UTC by tykhan

[DEMO LINK](https://tykhan.github.io/react_goods-selector/)

2020-09-03 10:04 UTC, kostyasabada approved these changes
Good!

2020-09-03 16:26 UTC, vkryvytskyy requested changes

2020-09-03 16:26 UTC, vkryvytskyy commented on src/App.js
> +    selected: '',
probably you don't need status, remove it

2020-09-03 16:26 UTC, vkryvytskyy commented on src/App.js
> +          {goodsFromServer.map(goods => (
```suggestion
          {goodsFromServer.map(good => (
```
this is one good

2020-09-03 16:26 UTC, vkryvytskyy commented on src/App.js
> +        <h1 className=" status">{status}</h1>
```suggestion
        <h1 className=" status">{selected ? `${selected} is in basket` : 'empty'}</h1>
```

2020-09-03 16:28 UTC, vkryvytskyy reviewed
without event.targe.textContent looks more readable, i think

2020-09-03 16:28 UTC, vkryvytskyy commented on src/App.js
> +  };
```suggestion
  savedGoods = (good) => {
    this.setState({
      selected: good,
    });
  };
```

2020-09-03 16:28 UTC, vkryvytskyy commented on src/App.js
> +                onClick={this.savedGoods}
```suggestion
                onClick={() => this.savedGoods(good)}
```

2020-09-03 17:20 UTC, tykhan commented on src/App.js
> +          {goodsFromServer.map(goods => (
<img width="728" alt="Знімок екрана 2020-09-03 о 20 18 09" src="https://user-images.githubusercontent.com/62352586/92146771-dc448c00-ee22-11ea-90a7-1a28bbd28a87.png">

2020-09-04 07:21 UTC, vkryvytskyy approved these changes

2020-09-04 07:21 UTC, vkryvytskyy commented on src/App.js
> +        </button>
show this button only when some goods is selected

2023-01-29 14:38 UTC, closed without merging