solution
mate-academy/react_goods-selector pull request #173
Opened 2021-03-17 19:29 UTC by yashnyi

[DEMO LINK](https://yashnyi.github.io/react_goods-selector/)

2021-03-18 13:03 UTC, Jastler approved these changes

2021-03-18 13:58 UTC, Vladimir-Beliy requested changes

2021-03-18 13:58 UTC, Vladimir-Beliy commented on src/App.js
> +    });
используй callback и prevState

2021-03-18 13:58 UTC, Vladimir-Beliy commented on src/App.js
> +    });
тут тоже

2021-03-18 13:58 UTC, Vladimir-Beliy commented on src/App.js
> +                    'are selected'
раздели логику

2021-03-19 15:50 UTC, yashnyi commented on src/App.js
> +                    'are selected'
если ты о разбивке на компоненты 😅
![image](https://user-images.githubusercontent.com/38386508/111807264-72ca2d80-88db-11eb-990d-af80c1ef026e.png)

2021-03-19 16:04 UTC, Vladimir-Beliy approved these changes

2025-09-01 20:49 UTC, closed without merging