Develop
mate-academy/react_goods-selector pull request #174
Opened 2021-03-18 10:08 UTC by Jastler

[DEMO LINK](https://jastler.github.io/react_goods-selector/)

2021-03-18 11:38 UTC, yashnyi approved these changes

2021-03-18 11:38 UTC, yashnyi commented on src/App.js
> +          ))}
Здається, щось тут не так з форматуванням пішло) 
Тяжко читати такий код

2021-03-18 13:56 UTC, Vladimir-Beliy requested changes

2021-03-18 13:56 UTC, Vladimir-Beliy commented on src/App.js
> +      });
используй callback и prevState

2021-03-18 13:56 UTC, Vladimir-Beliy commented on src/App.js
> +      )],
зачем создавать копию если фильтр вернет новый массив

2021-03-18 13:56 UTC, Vladimir-Beliy commented on src/App.js
> +      <div className="App">
раздели на несколько компонентов

2021-03-18 14:19 UTC, Jastler commented on src/App.js
> +      <div className="App">
Блин) а в задании было написано не делать компоненты

2021-03-19 10:53 UTC, Vladimir-Beliy approved these changes

2026-05-12 17:04 UTC, closed without merging