solved
mate-academy/react_goods-selector pull request #200
Opened 2021-04-05 12:40 UTC by JohnCrownHC

[DEMO LINK](https://JohnCrownHC.github.io/react_goods-selector/)

2021-04-05 18:40 UTC, MaxZadorozhniy approved these changes

2021-04-06 08:38 UTC, Denchepornyuk requested changes
було б круто зробити, щоб кнопка remove видаляла не всі, а по одному елементу
![image](https://user-images.githubusercontent.com/37452763/113681708-f735f200-96ca-11eb-9456-b1d0484a9e26.png)

2021-04-06 08:38 UTC, Denchepornyuk commented on src/App.js
> +      selected: [...prevState.selected, good],
🔥

2021-04-06 08:38 UTC, Denchepornyuk commented on src/App.js
> +            {` ${this.listRenderer()}`}
такі функції краще викликати там де ти робиш деструктуризацію state, над return і під render, зберігати в змінну результат функції і в h2 записати змінну

2021-04-06 08:38 UTC, Denchepornyuk commented on src/App.js
> +            <span className="goods__n">
```suggestion
            <span className="goods__length">
```

2021-04-06 08:38 UTC, Denchepornyuk commented on src/App.js
> +            onClick={() => this.clearGoods()}
якщо clearGoods не приймає параметрів то не потрібно огортати його в стрілочку функцію
```suggestion
            onClick={this.clearGoods}
```

2021-04-06 08:38 UTC, Denchepornyuk commented on src/App.js
> +                  ).length || null}
не роби фільтрацію там де пишеш html, це можна зробити знову ж над return і під render, а тут написати ось так
```
{yourVariable.length && (
  <div className="products__counter">
    {yourVariable.length}
  </div>
)}
```

yourVariable -  це має бути змінна в якій буде відфільтрований масив selected

2021-04-06 10:38 UTC, Denchepornyuk approved these changes

2024-04-18 12:34 UTC, closed without merging