first commit
mate-academy/react_goods-selector pull request #23
Opened 2020-09-03 12:22 UTC by zarva6596

[DEMO LINK](https://zarva6596.github.io/react_goods-selector/)

2020-09-03 16:34 UTC, vkryvytskyy requested changes
<img width="419" alt="image" src="https://user-images.githubusercontent.com/38065883/92142148-13fc0580-ee1c-11ea-86c8-af79c5209a86.png">
please align it vertically

2020-09-03 16:34 UTC, vkryvytskyy commented on src/App.js
> +    document.querySelector('.App__list--active').className = 'App__list';
don't use querySelectors in React

2020-09-03 16:34 UTC, vkryvytskyy commented on src/App.js
> +    close: false,
you need only one field in state for completing this task

2020-09-03 16:34 UTC, vkryvytskyy commented on src/App.js
> +            </button>
```suggestion
            {!!selector && <button
              type="button"
              className={close && 'App__close'}
              onClick={this.closeButton}
            >
              {close}
            </button>}
```
if something is selected, then button is showing up, if it's false in selector, button will not show up

2020-09-03 16:34 UTC, vkryvytskyy commented on src/App.js
> +        {goodsFromServer.map(a => (
```suggestion
        {goodsFromServer.map(good => (
```
what is `a`?

2020-09-03 16:34 UTC, vkryvytskyy commented on src/App.js
> +              className="App__list"
```suggestion
              className={selector === good ? 'selected' : ''}
```

2020-09-04 07:26 UTC, vkryvytskyy requested changes

2020-09-04 07:26 UTC, vkryvytskyy commented on src/App.js
> +            }}
don't use inline styles

2020-09-04 07:26 UTC, vkryvytskyy commented on src/App.js
>            <p>
where is key?

2020-09-04 07:26 UTC, vkryvytskyy commented on src/App.js
> +            className={selector && 'close'}
class name should describe what it makes, `visible` is more meaningful in this case

2020-09-07 06:56 UTC, Denchepornyuk approved these changes

2024-07-03 16:18 UTC, closed without merging