solution
mate-academy/react_goods-selector pull request #230
Opened 2021-05-23 19:22 UTC by Andriykooo

[DEMO LINK](https://Andriykooo.github.io/react_goods-selector/)

2021-05-24 05:11 UTC, victor-arutiunov reviewed
Nice work!

2021-05-24 05:11 UTC, victor-arutiunov commented on src/App.jsx
> +                  selectedGood.includes(item)
Good!

2021-05-24 11:23 UTC, mykola-yarchuk requested changes

2021-05-24 11:23 UTC, mykola-yarchuk commented on src/App.jsx
> +    selectedGood: ['Jam'],
```suggestion
    selectedGoods: ['Jam'],
```

2021-05-24 11:23 UTC, mykola-yarchuk commented on src/App.jsx
> +    this.goods = [...this.state.selectedGood];
there is no reason to that, just save your goods in the state

2021-05-24 11:23 UTC, mykola-yarchuk commented on src/App.jsx
> +    this.setState({ selectedGood: this.goods });
use state only

2021-05-24 11:23 UTC, mykola-yarchuk commented on src/App.jsx
> +    this.setState({ selectedGood: this.goods });
only state

2021-05-24 11:23 UTC, mykola-yarchuk commented on src/App.jsx
> +    this.setState({ selectedGood: this.goods });
leave only usage of state

2021-05-24 11:23 UTC, mykola-yarchuk commented on src/App.jsx
> +            ? `${selectedGood.join(', ')} is selected`
good advice from victor-arutinov

2021-05-24 11:23 UTC, mykola-yarchuk commented on src/App.jsx
> +                select
you can not only use different methods but also show different text inside the button

2021-05-24 15:29 UTC, mykola-yarchuk requested changes
good job, but you can simplify it, a lot.

2021-05-24 15:29 UTC, mykola-yarchuk commented on src/App.jsx
> +      return item;
```suggestion
      if (array.length > 1 && index === array.length - 2) {
          return `${item} and ${array[index + 1]}`;
      }

      return item;
```

2021-05-24 15:29 UTC, mykola-yarchuk commented on src/App.jsx
> +          }
you can simplify this, it can be implemented easier.

2021-05-24 15:29 UTC, mykola-yarchuk commented on src/App.jsx
> +              ? preparedTitleGoods.slice(0, selectedGoods.length - 1).join(', ')
em what you trying to achieve with that `slice`??

2021-05-25 07:06 UTC, mykola-yarchuk requested changes

2021-05-25 07:06 UTC, mykola-yarchuk commented on src/App.jsx
> +        }
```suggestion
        {goodsIsSelected && (
          <button type="button" onClick={this.clearItems}>
            X
          </button>
        )}
```

2021-05-25 07:06 UTC, mykola-yarchuk commented on src/App.jsx
> +              className={`app__item ${selectedGoods.includes(item)
you can create some variable (`isIncluded` for example) inside callback in `map` method before you return `<li>`, and use this variable in all places where you need it. with this approach, you can use the method includes only once

2021-05-25 07:06 UTC, mykola-yarchuk commented on src/App.jsx
> +// });
remove that

2021-05-25 07:06 UTC, mykola-yarchuk commented on src/App.jsx
> +            : ' No goods selected'
try to create some extra variables, this mess really hard to read

2021-05-25 12:47 UTC, mykola-yarchuk approved these changes

2022-09-21 14:37 UTC, closed without merging