Solution
mate-academy/react_goods-selector pull request #28
Opened 2020-09-03 14:56 UTC by 1nsider21

- [DEMO LINK](https://1nsider21.github.io/react_goods-selector/)

2020-09-03 15:00 UTC, zarva6596 approved these changes

2020-09-03 16:21 UTC, vsm2k17 requested changes
Крутий підхід, але давай так як в завданні сказано

2020-09-03 16:21 UTC, vsm2k17 commented on src/App.scss
> +  }
Хитро, але в завданні сказано додати клас
<img width="673" alt="Screenshot 2020-09-03 at 19 18 07" src="https://user-images.githubusercontent.com/35385361/92140859-56bcde00-ee1a-11ea-81c8-1298223fe50c.png">
і робити це треба динамічно , в залежності від значення яке знаходиться в state

2020-09-04 07:59 UTC, vsm2k17 approved these changes

2020-09-04 07:59 UTC, vsm2k17 commented on src/App.js
> +              }
це випадок коли у пригоді стане бібліотека classnames

2023-08-22 11:54 UTC, closed without merging