solution
mate-academy/react_goods-selector pull request #318
Opened 2021-07-26 05:40 UTC by gponomarenko

[DEMO LINK](https://gponomarenko.github.io/react_goods-selector/)

2021-07-26 09:34 UTC, VVVoloshina approved these changes
Очень крутое решение)

2021-07-26 11:02 UTC, danylo-onishchuk requested changes
Нужно дополнительные строки: 
is selected
are selected

2021-07-26 11:57 UTC, gponomarenko commented
Оновив.

2021-07-26 12:00 UTC, gponomarenko commented
> Очень крутое решение)

Дякую, приємно. Та заради обєктивності на ревью (одразу після свого першого комміта) побачив сильно кращу реалізацію, зокрема із застосуванням функції для виводу тексту, стилів з UI.

2021-07-26 15:17 UTC, danylo-onishchuk requested changes

2021-07-26 15:17 UTC, danylo-onishchuk commented on src/App.jsx
> +                    <React.Fragment>
зачем фрагмент?

2021-07-26 15:17 UTC, danylo-onishchuk commented on src/App.jsx
> +                      <li>
где ключ?

2021-07-26 15:17 UTC, danylo-onishchuk commented on src/App.jsx
> +          !selectedGoods.length
оооооооочень сложная конструкция. попробуй избежать переписывания списка дважды.

2021-07-26 15:50 UTC, gponomarenko commented on src/App.jsx
> +                    <React.Fragment>
Видалив

2021-07-26 15:52 UTC, gponomarenko commented on src/App.jsx
> +                      <li>
тут немає, в відкоригованому комміті є

2021-07-26 15:53 UTC, gponomarenko commented on src/App.jsx
> +          !selectedGoods.length
спростив

2021-07-27 08:16 UTC, danylo-onishchuk requested changes

2021-07-27 08:16 UTC, danylo-onishchuk commented on src/App.jsx
> +                  key="good"
ты используешь для всех элементов один и тот же ключ: строку good

2021-07-27 08:51 UTC, gponomarenko commented on src/App.jsx
> +                  key="good"
Дякую, тепер побачив!

2021-07-27 08:53 UTC, danylo-onishchuk approved these changes

2023-11-06 14:47 UTC, closed without merging