React_goods-selector created
mate-academy/react_goods-selector pull request #352
Opened 2021-09-06 05:22 UTC by Andrii-Pinchuk

2021-09-06 06:22 UTC, UlaDutchak approved these changes

2021-09-06 17:51 UTC, Denchepornyuk requested changes
![Screenshot 2021-09-06 at 20 51 09](https://user-images.githubusercontent.com/37452763/132250439-8ff5b84d-1906-4369-a654-e0f8bbcce1ec.png)

було б круто добавляти стилі на виділені елементи

2021-09-06 17:51 UTC, Denchepornyuk commented on src/App.tsx
> +        )}
```suggestion
        {selectedGoods.length && (
          <button
            className="card__button card__button--reset"
            type="button"
            onClick={resetState}
          >
            Clear
          </button>
        )}
```

2021-09-07 13:56 UTC, Denchepornyuk approved these changes

2021-09-07 13:56 UTC, Denchepornyuk commented on src/App.tsx
> +    }));
```suggestion
    this.setState((currentState) => ({
      selectedGoods: [...currentState.selectedGoods, good],
    }));
```

2025-10-29 17:25 UTC, closed without merging