solution
mate-academy/react_goods-selector pull request #428
Opened 2021-10-15 22:21 UTC by Tarasulko

[DEMO LINK](https://tarasulko.github.io/react_goods-selector/)

2021-10-18 08:01 UTC, aliceblunt8 requested changes

2021-10-18 08:01 UTC, aliceblunt8 commented on src/App.tsx
> +                    onClick={() => this.onClickGoodSelectHandler(index)}
```suggestion
                    onClick={() => this.selectGood(good)}
```

2021-10-18 08:01 UTC, aliceblunt8 commented on src/App.tsx
> +                    onClick={() => this.onClickGoodDismissHandler(index)}
```suggestion
                    onClick={() => this.dismissGood(good)}
```

2021-10-25 03:50 UTC, mgrinko approved these changes
Учти на будущее

2024-10-22 13:51 UTC, closed without merging