Develop
mate-academy/react_goods-selector pull request #449
Opened 2021-11-09 18:40 UTC by cyb1ove

[DEMO LINK](https://cyb1ove.github.io/react_goods-selector/)

2021-11-09 20:25 UTC, dima-narozhnyi reviewed
1. Save a `selectedGood` in the `App`. Let it be `Jam` by default
2. The `h1` should always show the name of the selected good `Jam is selected`
3.  The clear button should not be visible if there is no selected good

2021-11-10 13:17 UTC, solaryasha requested changes
<img width="466" alt="Screenshot 2021-11-10 at 15 13 49" src="https://user-images.githubusercontent.com/32794096/141119981-b47588a8-8c61-4b94-8764-f13303ba71a6.png">
Якщо вибираю більше двох елементів, то вони не додаються в корзину

2021-11-10 13:17 UTC, solaryasha commented on src/App.tsx
> +      const jointByAnd = activeGoods.splice(-2).join(' and ');
Не потрібно мутувати масив

2021-11-10 13:31 UTC, solaryasha approved these changes

2025-01-20 16:31 UTC, closed without merging