1
mate-academy/react_goods-selector pull request #493
Opened 2021-12-11 17:42 UTC by serhii-dvorets

https://serhii-dvorets.github.io/react_goods-selector/

2021-12-13 12:48 UTC, danylo-onishchuk requested changes
Add button X for to the h1 to clear the selection. (Set empty string '')

2022-01-12 14:35 UTC, aliceblunt8 requested changes

2022-01-12 14:35 UTC, aliceblunt8 commented on src/App.tsx
> +  makephrase = (array: string[]) => {
```suggestion
  selectedGoodsTitle = (array: string[]) => {
```

2022-01-12 14:35 UTC, aliceblunt8 commented on src/App.tsx
> +            <p>
why do you need p?

2022-01-12 14:35 UTC, aliceblunt8 commented on src/App.tsx
> +          goodsFromServer.map((item) => (
add key

2022-01-12 14:35 UTC, aliceblunt8 commented on src/App.tsx
> +                  }}
move to function

2022-01-12 15:03 UTC, serhii-dvorets commented on src/App.tsx
> +          goodsFromServer.map((item) => (
What key?

2022-01-13 12:43 UTC, danylo-onishchuk approved these changes

2024-05-27 08:42 UTC, closed without merging