Done
mate-academy/react_goods-selector pull request #539
Opened 2022-01-20 21:04 UTC by MaksimusCRS

[DEMO LINK](https://MaksimusCRS.github.io/react_goods-selector/)

2022-01-21 06:37 UTC, luckdenny approved these changes

2022-01-21 13:52 UTC, Elena-brv requested changes

2022-01-21 13:52 UTC, Elena-brv commented on src/App.tsx
> +      return {
avoid return

2022-01-21 13:52 UTC, Elena-brv commented on src/App.tsx
> +        return `${[...selectedGoods].splice(0, selectedGoods.length - 1).join(', ')} and ${selectedGoods[selectedGoods.length - 1]} are selected`;
better divide it into different variables to simpler understand your logic

2022-01-21 13:52 UTC, Elena-brv commented on src/App.tsx
> +                })}
```suggestion
                className={classNames(
                  'list__item', 
                  { 'list__item--selected': isSelected }
                )}
```

2022-01-24 15:08 UTC, danheim approved these changes

2022-01-24 15:08 UTC, danheim commented on src/App.tsx
> +      return {
в верхнем this.setState написали avoid return
это значит что нужно пройтись по всему коду и посмотреть подобные ошибки

2022-10-20 17:45 UTC, closed without merging