done
mate-academy/react_goods-selector pull request #60
Opened 2020-10-22 13:12 UTC by aionova

[DEMO LINK](https://aionova.github.io/react_goods-selector/)

2020-10-22 14:13 UTC, yazheviks approved these changes
Класс!

2020-10-23 09:55 UTC, aliceblunt8 requested changes

2020-10-23 09:55 UTC, aliceblunt8 commented on src/components/goodsList/GoodsList.jsx
> +export const GoodsList = ({ preparedGoods, selectTodo, deleteTodo, selected }) => (
don't disable eslint in this case, move arguments to the new lines

2020-10-23 09:55 UTC, aliceblunt8 commented on src/components/Good/Good.js
> +        ? 'good__item selected' : 'good__item'}
use className library
https://www.npmjs.com/package/classnames
also Misha recorder a video about it
https://www.youtube.com/watch?v=l6af8bEqP9E&feature=youtu.be

2020-10-26 09:35 UTC, Vladimir-Beliy requested changes

2020-10-26 09:35 UTC, Vladimir-Beliy commented on src/App.js
> +    if ((event.metaKey || event.ctrlKey)
```suggestion
    } else if ((event.metaKey || event.ctrlKey)
```

2020-10-26 09:35 UTC, Vladimir-Beliy commented on src/App.js
> +    if (this.state.selected.includes(selectedTodo)) {
```suggestion
    } else if (this.state.selected.includes(selectedTodo)) {
```

2020-10-26 09:35 UTC, Vladimir-Beliy commented on src/App.js
> +        .forEach(selectedItem => selectedItem.classList.remove('selected'));
мы не работаем с ДОМ-ом на прямую когда используем реакт, только через реакт

2020-10-26 10:53 UTC, aionova commented on src/App.js
> +    if (this.state.selected.includes(selectedTodo)) {
@Vladimir-Beliy а зачем else если в каждом if есть return?

2020-10-26 11:44 UTC, Vladimir-Beliy commented on src/App.js
> +    if (this.state.selected.includes(selectedTodo)) {
я считаю что так читабельнее, сразу понятно что будет выполнено что то одно из множества. Тут нужно сделать вообще по другому, тебе нужно объявить переменную (внутри метода) и в нее записывать то что ты хочешь записать в state, и в конце вызвать один раз setState

2020-10-26 11:57 UTC, Vladimir-Beliy requested changes
/

2020-10-26 14:34 UTC, Vladimir-Beliy approved these changes

2023-09-27 08:15 UTC, closed without merging