Develop
mate-academy/react_goods-selector pull request #601
Opened 2022-03-17 12:39 UTC by SanyaBratashchuk

https://SanyaBratashchuk.github.io/react_goods-selector/

2022-03-18 11:34 UTC, solaryasha requested changes

2022-03-18 12:58 UTC, SanyaBratashchuk commented on src/App.tsx
> +    return () => { };
щоб нічого не відбувалося, якщо товар вже є в списку, просто return не пропускав чи то лінтер чи то typescript, бо він боїться,шо onClick отримає undefined

2022-03-20 17:27 UTC, SanyaBratashchuk commented on src/App.tsx
> +    return () => { };
> щоб нічого не відбувалося, якщо товар вже є в списку, просто return не пропускав чи то лінтер чи то typescript, бо він боїться,шо onClick отримає undefined

Затупив) додав це в процесі, коли в мене ше не мінялася кнопка і було можливо додати один і той самий продукт багато разів

2022-03-22 09:28 UTC, Ihor-Karpyn approved these changes

2026-05-02 10:22 UTC, closed without merging