solution
mate-academy/react_goods-selector pull request #635
Opened 2022-04-19 14:53 UTC by vlad-trundenko

[DEMO LINK](https://vlad-trundenko.github.io/react_goods-selector/)

2022-04-20 06:35 UTC, Bohdan-Maksymiuk requested changes

2022-04-20 06:35 UTC, Bohdan-Maksymiuk commented on src/App.tsx
> +    selectedGood: [goodsFromServer[8]],
```suggestion
    selectedGood: [],
```
you can left like this in initial state

2022-04-20 06:35 UTC, Bohdan-Maksymiuk commented on src/App.tsx
> +                className={selectedGood.includes(product) ? 'selected' : ''}
use classNames lib
https://www.npmjs.com/package/classnames

2022-04-26 12:53 UTC, ArturErmolenko approved these changes
👍

2023-02-12 11:04 UTC, closed without merging