V1
mate-academy/react_goods-selector pull request #639
Opened 2022-04-21 12:47 UTC by ivan-major

https://ivan-major.github.io/react_goods-selector/

2022-04-22 14:20 UTC, aliceblunt8 requested changes

2022-04-22 14:20 UTC, aliceblunt8 commented on src/App.tsx
> +    const selectGoods = () => {
```suggestion
    const getSelectedGoods = () => {
```

2022-04-22 14:20 UTC, aliceblunt8 commented on src/App.tsx
> +                <li className={classNames(
first li, then div 
cause ul > li

2022-04-22 14:20 UTC, aliceblunt8 commented on src/App.tsx
> +                    }));
move to separate handler

2022-04-22 14:20 UTC, aliceblunt8 commented on src/App.tsx
> +                  }}
move to separate handler

2022-04-22 14:20 UTC, aliceblunt8 commented on src/App.tsx
> +              }}
move to separate handler

2022-04-26 12:57 UTC, ArturErmolenko approved these changes

2025-01-26 12:55 UTC, closed without merging