readme update
mate-academy/react_goods-selector pull request #64
Opened 2020-10-24 13:53 UTC by AndriiManyak

[DEMO LINK](https://andriimanyak.github.io/react_goods-selector/)

2020-10-26 15:50 UTC, AlinaMatuschak approved these changes

2020-10-27 10:01 UTC, Vladimir-Beliy requested changes
в чате писал за эту таску, можешь попробовать использовать этот метод

2020-10-27 10:01 UTC, Vladimir-Beliy commented on src/App.js
> +  }
не понимаю что тут происходит

2020-10-28 08:31 UTC, Vladimir-Beliy approved these changes

2026-02-12 22:54 UTC, closed without merging