list with buttons
mate-academy/react_goods-selector pull request #645
Opened 2022-05-05 13:58 UTC by misha200119

[DEMO LINK](https://misha200119.github.io/react_goods-selector/)

2022-05-10 07:07 UTC, plankton9991 approved these changes
Nice work with a small count of code 👍

2022-05-10 15:50 UTC, Andr1yK requested changes
Хороший початок🚀
та потрібні правки))

2022-05-10 15:50 UTC, Andr1yK commented on src/App.tsx
> +      + ' selected';
Можна спростити це, використовуй slice i join)

2022-05-10 15:50 UTC, Andr1yK commented on src/App.tsx
> +              <li
```suggestion
          {goods.map(good => (
              <li
```

2022-05-10 15:50 UTC, Andr1yK commented on src/App.tsx
> +                  }}
винеси в окрему функції)

2022-05-10 15:50 UTC, Andr1yK commented on src/App.tsx
> +            this.forceUpdate();
🥲

2022-05-10 15:50 UTC, Andr1yK commented on src/App.tsx
> +            this.forceUpdate();
не юзай forceUpdate

2022-05-10 17:46 UTC, misha200119 commented on src/App.tsx
> +            this.forceUpdate();
на тот момент я ещё не знал что всё нужно делать через satState (immutable)

2022-05-12 07:59 UTC, Andr1yK commented on src/App.tsx
> +            this.forceUpdate();
Круто, що тепер знаєш))

2022-05-12 08:02 UTC, Andr1yK approved these changes

2025-08-10 12:53 UTC, closed without merging