Solution
mate-academy/react_goods-selector pull request #650
Opened 2022-05-07 09:50 UTC by ivan-kadykalo

[DEMO LINK](https://ivan-kadykalo.github.io/react_goods-selector/)

2022-05-09 16:29 UTC, Yurii837 approved these changes
Looks good.

2022-05-09 16:29 UTC, Yurii837 commented on src/App.tsx
> +  componentDidMount() {
Заморочився)

2022-05-09 16:35 UTC, Yurii837 requested changes

2022-05-10 15:28 UTC, Andr1yK requested changes
Хороша робота, та треба пофіксити setState

2022-05-10 15:28 UTC, Andr1yK commented on src/App.tsx
> +    this.setState({
Якщо ти опираєшся на старий стейт, то потрібно юзати функціональний setState

2022-05-10 15:28 UTC, Andr1yK commented on src/App.tsx
> +    const { selectedGoods } = this.state;
і тут

2022-05-11 08:36 UTC, Andr1yK approved these changes

2023-08-08 17:39 UTC, closed without merging