my solution
mate-academy/react_goods-selector pull request #765
Opened 2022-07-12 10:01 UTC by Pavlo000

[DEMO LINK](https://Pavlo000.github.io/react_goods-selector/)

2022-07-12 16:42 UTC, MariiaNH requested changes
Привіт, потрібно трошки доробити код таким чином, щоб можна було обирати декілька продуктів, а не тільки один. 

Все інше чудово працює)

2022-07-12 16:43 UTC, Pavlo000 commented
Це ж вроді не обовязковий пункт

2022-07-12 16:49 UTC, MariiaNH commented
> 

Хм, впевнена, що бу обов'язковим - але щойно переглянула завдання - дійсно в обов'язкових пунктах цього немає (і опис завдання змінено 2 години тому). 

Тоді все чудово - апрувлю)

2022-07-12 16:49 UTC, MariiaNH approved these changes

2022-07-13 08:57 UTC, mykola-koval approved these changes

2022-07-13 08:57 UTC, mykola-koval commented on src/App.tsx
> +        {selectedGood && (
```suggestion
        </h1>
        
        {selectedGood && (
```

2022-07-13 08:57 UTC, mykola-koval commented on src/App.tsx
> +        <ul className="list">
```suggestion
        )}
        
        <ul className="list">
```

2022-07-13 08:57 UTC, mykola-koval commented on src/App.tsx
> +                <button
```suggestion
                </button>
                
                <button
```

2024-11-26 18:41 UTC, closed without merging